// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8IzLjRdtP9omckjcsnHH_syp6WIKRcSc',
    appId: '1:359332545659:web:1a1335192e7e8152c28ede',
    messagingSenderId: '359332545659',
    projectId: 'pufflab-969c3',
    authDomain: 'pufflab-969c3.firebaseapp.com',
    storageBucket: 'pufflab-969c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAp84_NYrSq6-D_NqrF_x05bCeN6x08_Q',
    appId: '1:359332545659:android:44f8b430d0d44f08c28ede',
    messagingSenderId: '359332545659',
    projectId: 'pufflab-969c3',
    storageBucket: 'pufflab-969c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkXCfF7NQjpjqr-n7UpEKUB575184AshI',
    appId: '1:359332545659:ios:f917fe256f051c9fc28ede',
    messagingSenderId: '359332545659',
    projectId: 'pufflab-969c3',
    storageBucket: 'pufflab-969c3.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkXCfF7NQjpjqr-n7UpEKUB575184AshI',
    appId: '1:359332545659:ios:f917fe256f051c9fc28ede',
    messagingSenderId: '359332545659',
    projectId: 'pufflab-969c3',
    storageBucket: 'pufflab-969c3.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8IzLjRdtP9omckjcsnHH_syp6WIKRcSc',
    appId: '1:359332545659:web:d9cf5c7e65c54fbcc28ede',
    messagingSenderId: '359332545659',
    projectId: 'pufflab-969c3',
    authDomain: 'pufflab-969c3.firebaseapp.com',
    storageBucket: 'pufflab-969c3.firebasestorage.app',
  );
}
